### ISSUE TITLE
Update jekyll build config to match github pages

### ISSUE THREAD

**Issue by MartijnR** [getodk/xforms-spec#83]
Seems there is a small difference, e.g. in list generation in introduction.

**Comment by lognaturel** [comment]
Oh, hah, I missed this. #84 may not be necessary, then.

Edit: just kidding, it still is. But they're related.

**Comment by MartijnR** [comment]
I played around with this but cannot reproduce it locally. Not worth spending more time on, I think (especially now that the new line has fixed it). Will close.

For posterity, this is what I tried:
```yaml
# GitHub settings that cannot be changed if published with GitHub pages
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
# Customizable settings
  input: GFM
  hard_wrap: false
title: ODK XForms Specification 
description: "Documents the XForms and OpenRosa-derived form specification as supported by ODK-compliant tools."
baseurl: ""
url: ""
collections:
- sections
```
